# Data Aggregation and Grouping

La agregación de datos es una de las técnicas más poderosas en el análisis de datos. Nos permite segmentar nuestro conjunto de datos en grupos y aplicar cálculos matemáticos (como sumas, promedios o conteos) a cada segmento. En este cuaderno exploraremos el uso del método `.groupby()` y cómo realizar análisis de tendencias.

In [23]:
import pandas as pd

# Escenario 1: Transacciones simples de productos por categoría
data = {
    "Categoria": ["A", "B", "A", "C", "B", "A"],
    "Valor": [10, 20, 30, 40, 50, 60],
    "Cantidad": [4, 1, 6, 2, 3, 5]
}

df = pd.DataFrame(data)
print("--- Dataset de Transacciones ---")
df

--- Dataset de Transacciones ---

  Categoria  Valor  Cantidad
0         A     10         4
1         B     20         1
2         A     30         6
3         C     40         2
4         B     50         3
5         A     60         5

## 1. Agrupaciones Simples (Single Grouping)
El método `.groupby()` divide los datos basándose en los valores de una columna. Luego, encadenamos una función estadística para obtener un resultado resumido.

In [24]:
print("--- Suma de Valores por Categoría ---")
suma_por_categoria = df.groupby("Categoria")["Valor"].sum()
print(suma_por_categoria)

print("\n--- Promedio de Valores por Categoría ---")
media_por_categoria = df.groupby("Categoria")["Valor"].mean()
print(media_por_categoria)

print("\n--- Frecuencia (Conteo) por Categoría ---")
recuento_por_categoria = df.groupby("Categoria")["Valor"].count()
print(recuento_por_categoria)

--- Suma de Valores por Categoría ---
Categoria
A    100
B     70
C     40
Name: Valor, dtype: int64

--- Promedio de Valores por Categoría ---
Categoria
A    33.333333
B    35.000000
C    40.000000
Name: Valor, dtype: float64

--- Frecuencia (Conteo) por Categoría ---
Categoria
A    3
B    2
C    1
Name: Valor, dtype: int64

## 2. Múltiples Funciones con `.agg()`
En lugar de calcular métricas una por una, el método `.agg()` nos permite aplicar múltiples funciones estadísticas simultáneamente a nuestros grupos, devolviendo un DataFrame muy limpio.

In [25]:
print("--- Múltiples Agregaciones Simultáneas ---")
agregados_por_categoria = df.groupby("Categoria")["Valor"].agg(["sum", "mean", "count"])
agregados_por_categoria

--- Múltiples Agregaciones Simultáneas ---

           sum       mean  count
Categoria
A          100  33.333333      3
B           70  35.000000      2
C           40  40.000000      1

## 3. Agrupación Multinivel (MultiIndex)
Podemos agrupar por más de una categoría pasando una lista al método `.groupby()`. Esto crea una jerarquía o "MultiIndex".

In [26]:
# Añadimos una nueva dimensión a nuestros datos (ej. Sucursal o Grupo)
df["Grupo"] = ["G1", "G1", "G2", "G2", "G1", "G2"]

print("--- Suma de Valores por Grupo y Categoría ---")
suma_por_grupo_categoria = df.groupby(["Grupo", "Categoria"])["Valor"].sum()
suma_por_grupo_categoria

--- Suma de Valores por Grupo y Categoría ---

Grupo  Categoria
G1     A            10
       B            70
G2     A            90
       C            40
Name: Valor, dtype: int64

## 4. Ejercicio Práctico: Análisis de Tendencias de Ventas
En el mundo real, la agrupación se utiliza a menudo junto con datos temporales para analizar el rendimiento a lo largo del tiempo.

In [27]:
# Escenario 2: Registro de ventas diarias
datos_ventas = {
    "Fecha": ["2026-10-01", "2026-10-01", "2026-10-02", "2026-10-02", "2026-10-03", "2026-10-03"],
    "Producto": ["Producto A", "Producto B", "Producto A", "Producto B", "Producto A", "Producto B"],
    "Categoria": ["Electronica", "Ropa", "Electronica", "Ropa", "Electronica", "Ropa"],
    "Ventas": [100, 150, 200, 100, 300, 250]
}

df_ventas = pd.DataFrame(datos_ventas)
# Convertimos la columna 'Fecha' al tipo datetime para un manejo correcto de series de tiempo
df_ventas["Fecha"] = pd.to_datetime(df_ventas["Fecha"])

print("--- Ventas Totales por Categoría ---")
ventas_por_categoria = df_ventas.groupby("Categoria")["Ventas"].sum()
print(ventas_por_categoria)

print("\n--- Tendencia de Ventas Diarias ---")
ventas_por_fecha = df_ventas.groupby("Fecha")["Ventas"].sum()
print(ventas_por_fecha)

print("\n--- Desglose Diario por Producto ---")
ventas_por_fecha_producto = df_ventas.groupby(["Fecha", "Producto"])["Ventas"].sum()
print(ventas_por_fecha_producto)

--- Ventas Totales por Categoría ---
Categoria
Electronica    600
Ropa           500
Name: Ventas, dtype: int64

--- Tendencia de Ventas Diarias ---
Fecha
2026-10-01    250
2026-10-02    300
2026-10-03    550
Name: Ventas, dtype: int64

--- Desglose Diario por Producto ---
Fecha       Producto
2026-10-01  Producto A    100
            Producto B    150
2026-10-02  Producto A    200
            Producto B    100
2026-10-03  Producto A    300
            Producto B    250
Name: Ventas, dtype: int64