# DIE03: Excel Data I/O (Input/Output)

Excel sigue siendo la herramienta de negocio más utilizada en el mundo corporativo. Como analistas de datos, necesitamos poder extraer datos de hojas de cálculo complejas y, del mismo modo, exportar nuestros resultados a formatos `.xlsx` para que los clientes o gerentes puedan consumirlos.

Para interactuar con archivos Excel modernos, Python utiliza el motor `openpyxl`.

In [1]:
# Instalación del motor necesario para leer/escribir archivos .xlsx modernos
# En entornos de Jupyter, usamos '!' y '%' para ejecutar comandos de terminal
!python -m pip install --upgrade pip
%pip install openpyxl

Requirement already satisfied: pip in d:\Cursos\Python\.venv\Lib\site-packages (26.1.2)
Requirement already satisfied: openpyxl in d:\Cursos\Python\.venv\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in d:\Cursos\Python\.venv\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

# Escenario: Catálogo de inventario de una tienda de electrónica
inventario_data = [
    {"Producto": "Laptop",     "Marca": "Dell",      "Precio": 1200, "Stock": 15},
    {"Producto": "Smartphone", "Marca": "Samsung",   "Precio": 850,  "Stock": 30},
    {"Producto": "Tablet",     "Marca": "Apple",     "Precio": 600,  "Stock": 20},
    {"Producto": "Monitor",    "Marca": "LG",        "Precio": 320,  "Stock": 12},
    {"Producto": "Teclado",    "Marca": "Logitech",  "Precio": 45,   "Stock": 50},
    {"Producto": "Mouse",      "Marca": "Razer",     "Precio": 30,   "Stock": 65},
    {"Producto": "Audífonos",  "Marca": "Sony",      "Precio": 150,  "Stock": 25},
    {"Producto": "Impresora",  "Marca": "HP",        "Precio": 250,  "Stock": 10}
]

df_inventario = pd.DataFrame(inventario_data)

# Guardar el DataFrame en un archivo Excel
# CRÍTICO: index=False evita que se exporte la columna numérica del índice (0, 1, 2...)
df_inventario.to_excel('DIE03_electronics.xlsx', sheet_name='Productos', index=False)

print("Archivo Excel generado exitosamente.")
df_inventario

Archivo Excel generado exitosamente.

     Producto     Marca  Precio  Stock
0      Laptop      Dell    1200     15
1  Smartphone   Samsung     850     30
2      Tablet     Apple     600     20
3     Monitor        LG     320     12
4     Teclado  Logitech      45     50
5       Mouse     Razer      30     65
6   Audífonos      Sony     150     25
7   Impresora        HP     250     10

In [3]:
# Leer el archivo Excel especificando explícitamente el motor
df_productos_importados = pd.read_excel('DIE03_electronics.xlsx', engine='openpyxl')

print("--- DataFrame importado desde Excel ---")
df_productos_importados

--- DataFrame importado desde Excel ---

     Producto     Marca  Precio  Stock
0      Laptop      Dell    1200     15
1  Smartphone   Samsung     850     30
2      Tablet     Apple     600     20
3     Monitor        LG     320     12
4     Teclado  Logitech      45     50
5       Mouse     Razer      30     65
6   Audífonos      Sony     150     25
7   Impresora        HP     250     10